### ISSUE TITLE
Unable to run axegrinder on various sites "Error: Server terminated early with status 1"

### ISSUE THREAD

**Issue by syndy1989** [claflamme/axegrinder#1]
Hi, I'm trying things out with axegrinder.

OS- windows server 2012
Node-6.10.0
PhanjomJS-2.1.1
Axe-1.0.0
Selenium Webdriver-3.3.0

 I'm able to run axegrinder on very few sites. Its throwing error for most sites. Please find the error below.
`C:\Users\AppData\Roaming\npm\node_modules>axegrinder crawl https://gmail.
com

Building initial map. One moment, please...

✘ https://gmail.com/
  - Elements must have sufficient color contrast
  - Form elements must have labels

C:\Users\AppData\Roaming\npm\node_modules>axegrinder crawl https://flipka
rt.com

Building initial map. One moment, please...

✘ https://www.flipkart.com/mobile-apps
  - Buttons must have discernible text
  - Elements must have sufficient color contrast
  - Headings must not be empty
  - Form elements must have labels
  - Links must have discernible text
✘ https://www.flipkart.com/helpcentre
  - Buttons must have discernible text
  - Elements must have sufficient color contrast
  - Form elements must have labels
  - Links must have discernible text
✘ https://www.flipkart.com/buy-gift-voucher
  - <html> element must have a lang attribute
C:\Users\AppData\Roaming\npm\node_modules\axegrinder\node_modules\seleniu
m-webdriver\lib\promise.js:654
    throw error;
    ^

Error: Server terminated early with status 1
    at Error (native)
    at C:\Users\AppData\Roaming\npm\node_modules\axegrinder\node_modules\
selenium-webdriver\remote\index.js:242:20
    at ManagedPromise.invokeCallback_ (C:\Users\AppData\Roaming\npm\node_
modules\axegrinder\node_modules\selenium-webdriver\lib\promise.js:1379:14)
    at TaskQueue.execute_ (C:\Users\AppData\Roaming\npm\node_modules\axeg
rinder\node_modules\selenium-webdriver\lib\promise.js:2913:14)
    at TaskQueue.executeNext_ (C:\Users\AppData\Roaming\npm\node_modules\
axegrinder\node_modules\selenium-webdriver\lib\promise.js:2896:21)
    at asyncRun (C:\Users\AppData\Roaming\npm\node_modules\axegrinder\nod
e_modules\selenium-webdriver\lib\promise.js:2775:27)
    at C:\Users\AppData\Roaming\npm\node_modules\axegrinder\node_modules\
selenium-webdriver\lib\promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)`

What could be the problem. Any advise on this would be helpful. Thanks in advance

**Comment by ArmorDarks** [comment]
Same error.

I guess it's because we're trying to use it without Selenium server?

**Comment by claflamme** [comment]
This shouldn't be happening anymore in v2. The browser part is now done using nightmare/electron instead of selenium/phantomjs.
