### ISSUE TITLE
add support for basic auth

### ISSUE THREAD

**Issue by DanielRuf** [claflamme/axegrinder#3]

**Comment by claflamme** [comment]
Does using a standard HTTP auth URL not work? For example:

`http://username:password@mysite.com`

If not, that'd be a good addition for sure.

**Comment by DanielRuf** [comment]
that can be problematic in some cases eg when the password contains a `:` or an `@`, better provide two cli options which can be also used by CI tools.

**Comment by claflamme** [comment]
Good point, it's on my todo list 👍

**Comment by jenknight** [comment]
This is also a need for me.  Have you made progress, or if I implement something do you want me to contribute?

**Comment by DanielRuf** [comment]
Hm, I can plan to invest some time if it would be helpful.

**Comment by claflamme** [comment]
Hey, thanks for your interest. I put this tool on the backburner for a while, but I've got got a new project at work with some strict a11y requirements, so I'll probably be getting back into this shortly.

If you want to put together a pull request, I'd be happy to check it out, too.
